spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Ds/iAswKDOI2IBdXVlUbp+1ZYJs/loWNCyGaebesnH+oiH5A+vPEpYY09swmh46cg4LixzDn+SY=)
    username: ENC(W30pxDFoEU+LniYDtqL3zg==)
    password: ENC(N/y/BCe1NvxsQe1SNaQArA==)
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    com.team33.backend: debug
    org.springframework.web.servlet: trace
token:
  secret: Ds/iAswKDOI2IBdXVlUbp+1ZYJs/loWNCyGaebesnH+oiH5A+vPEpYY09swmh46cg4LixzDn+SY=
jasypt:
  encryptor:
    bean: stringEncryptor
